"""Render transparent API/report evidence when a signed-in UI capture is unavailable."""

import json
import sys
from datetime import timedelta, timezone
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
import config  # noqa: E402 - load LangSmith configuration before the client
from langsmith import Client  # noqa: E402

OUT = ROOT / "evidence"
FONT = Path("C:/Windows/Fonts/arial.ttf")
BOLD = Path("C:/Windows/Fonts/arialbd.ttf")


def font(size, bold=False):
    path = BOLD if bold else FONT
    return ImageFont.truetype(str(path), size) if path.exists() else ImageFont.load_default()


def canvas(title, subtitle, source):
    image = Image.new("RGB", (1500, 850), "#f4f7fb")
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle((42, 40, 1458, 810), radius=22, fill="white")
    draw.rounded_rectangle((42, 40, 1458, 200), radius=22, fill="#142a46")
    draw.rectangle((42, 155, 1458, 200), fill="#142a46")
    draw.text((80, 75), title, fill="white", font=font(40, True))
    draw.text((80, 135), subtitle, fill="#c7d6e8", font=font(23))
    draw.text((80, 765), source, fill="#536477", font=font(18))
    return image, draw


def render_traces(client):
    groups = {}
    for name in ("rag-query", "ab-rag-query"):
        groups[name] = list(client.list_runs(
            project_name=config.LANGSMITH_PROJECT,
            is_root=True,
            filter=f'eq(name, "{name}")',
            limit=100,
        ))
    image, draw = canvas(
        "LangSmith trace verification",
        f"Project: {config.LANGSMITH_PROJECT}  |  {len(groups['rag-query']) + len(groups['ab-rag-query'])} root traces",
        "Source: live LangSmith API. This is an API report, not a dashboard screenshot.",
    )
    for x, name in ((80, "rag-query"), (770, "ab-rag-query")):
        runs = groups[name]
        draw.rounded_rectangle((x, 230, x + 650, 330), radius=14, fill="#e8f1fb")
        draw.text((x + 25, 252), name, fill="#142a46", font=font(26, True))
        draw.text((x + 545, 245), str(len(runs)), fill="#1764a5", font=font(42, True))
        draw.text((x + 8, 365), "Recent root traces", fill="#344b62", font=font(24, True))
        for i, run in enumerate(runs[:8]):
            stamp = run.start_time.astimezone(timezone(timedelta(hours=7))).strftime("%d/%m %H:%M")
            status = "ERROR" if run.error else "OK"
            draw.text((x + 8, 410 + i * 40), f"{stamp}   ...{str(run.id)[-8:]}   {status}", fill="#23384f", font=font(20))
    image.save(OUT / "01_langsmith_traces.png")


def render_prompts(client):
    names = ("tran-dai-nhan-rag-prompt-v1", "tran-dai-nhan-rag-prompt-v2")
    found = {p.repo_handle: p for p in client.list_prompts(query="tran-dai-nhan-rag-prompt").repos}
    if not all(name in found for name in names):
        raise RuntimeError("Both Prompt Hub entries must exist before rendering evidence")
    image, draw = canvas(
        "Prompt Hub verification",
        "Two named prompt repositories, both pulled successfully",
        "Source: live LangSmith Prompt Hub API. This is an API report, not a UI screenshot.",
    )
    for i, name in enumerate(names):
        y = 240 + i * 220
        draw.rounded_rectangle((80, y, 1420, y + 185), radius=16, fill="#e8f1fb")
        draw.text((110, y + 28), name, fill="#142a46", font=font(31, True))
        draw.text((110, y + 88), f"Commits: {found[name].num_commits}", fill="#344b62", font=font(24))
        prompt = client.pull_prompt(name)
        system = prompt.messages[0].prompt.template
        description = system.split("Context:")[0].replace("\n", " ").strip()
        draw.text((110, y + 132), description[:105], fill="#344b62", font=font(18))
    image.save(OUT / "02_prompt_hub.png")


def render_scores():
    path = ROOT / "data" / "ragas_report.json"
    if not path.exists():
        return
    report = json.loads(path.read_text(encoding="utf-8"))
    image, draw = canvas(
        "RAGAS score comparison",
        "50 QA pairs evaluated with each prompt version",
        "Source: data/ragas_report.json generated by src/03_ragas_evaluation.py.",
    )
    draw.text((690, 245), "V1", fill="#1764a5", font=font(28, True))
    draw.text((1120, 245), "V2", fill="#b56721", font=font(28, True))
    for i, metric in enumerate(("faithfulness", "answer_relevancy", "context_recall", "context_precision")):
        y = 315 + i * 100
        v1 = report["prompt_v1_scores"][metric]
        v2 = report["prompt_v2_scores"][metric]
        draw.text((80, y + 13), metric, fill="#23384f", font=font(25, True))
        for x, score, color in ((570, v1, "#1764a5"), (1000, v2, "#b56721")):
            draw.rounded_rectangle((x, y, x + 280, y + 45), radius=9, fill="#e4e9ef")
            draw.rounded_rectangle((x, y, x + max(1, int(280 * score)), y + 45), radius=9, fill=color)
            draw.text((x + 300, y + 8), f"{score:.4f}", fill="#23384f", font=font(23, True))
    draw.text((80, 715), "Faithfulness target >= 0.8: " + ("MET" if report["target_met"] else "NOT MET"),
              fill="#13815b" if report["target_met"] else "#b94a48", font=font(25, True))
    image.save(OUT / "03_ragas_scores.png")


if __name__ == "__main__":
    OUT.mkdir(exist_ok=True)
    client = Client(api_key=config.LANGSMITH_API_KEY)
    render_traces(client)
    render_prompts(client)
    render_scores()
    print("Rendered verified evidence images in evidence/")
